// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;  // ✅ 수정됨!
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ Web 설정 추가!
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATfYwUbF0dJfygiiV-9m_ws9JzK9_n-W4',
    appId: '1:635507076709:web:d7d6f7f32958f2d5924773',
    messagingSenderId: '635507076709',
    projectId: 'logistics-to-system',
    storageBucket: 'logistics-to-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpZ_65xL68NYh7jFlYXFGHj5UgtNDvAh0',
    appId: '1:635507076709:android:bc2dafc49476cf11a2e08c',
    messagingSenderId: '635507076709',
    projectId: 'logistics-to-system',
    storageBucket: 'logistics-to-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJiMm9MRSMYbtDui8dcJOjIRW8QNvKXFE',
    appId: '1:635507076709:ios:7e9c4d71ef689c49a2e08c',
    messagingSenderId: '635507076709',
    projectId: 'logistics-to-system',
    storageBucket: 'logistics-to-system.firebasestorage.app',
    iosBundleId: 'com.example.logisticsToApp',
  );
}